name: Deploy Frontend to Cloud Run

on:
  push:
    branches:
      - main
    paths:
      - 'frontend/**'
      - '.github/workflows/deploy-frontend.yml'
  workflow_dispatch:

env:
  PROJECT_ID: orangesage
  PROJECT_NUMBER: 117299588539
  SERVICE_NAME: orange-sage-frontend
  REGION: us-central1
  NODE_VERSION: '18'

jobs:
  deploy:
    name: Deploy Frontend
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Configure Docker for GCR
        run: |
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Build and Push Docker image
        working-directory: ./frontend
        run: |
          IMAGE_NAME="${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/orange-sage/${{ env.SERVICE_NAME }}:${{ github.sha }}"
          echo "Building frontend with BACKEND_URL: ${{ secrets.BACKEND_URL }}"
          docker build \
            --build-arg NEXT_PUBLIC_API_URL="${{ secrets.BACKEND_URL }}" \
            -t $IMAGE_NAME .
          docker push $IMAGE_NAME
          echo "IMAGE_NAME=$IMAGE_NAME" >> $GITHUB_ENV

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image ${{ env.IMAGE_NAME }} \
            --region ${{ env.REGION }} \
            --platform managed \
            --allow-unauthenticated \
            --port 3000 \
            --memory 512Mi \
            --cpu 1 \
            --min-instances 0 \
            --max-instances 10 \
            --timeout 300 \
            --service-account ${{ secrets.GCP_SERVICE_ACCOUNT_EMAIL }}

      - name: Get Service URL
        run: |
          SERVICE_URL=$(gcloud run services describe ${{ env.SERVICE_NAME }} --region ${{ env.REGION }} --format 'value(status.url)')
          echo "Frontend deployed to: $SERVICE_URL"
          echo "SERVICE_URL=$SERVICE_URL" >> $GITHUB_ENV

      - name: Test deployment
        run: |
          echo "Waiting for service to be ready..."
          sleep 15
          
          # Retry health check up to 5 times with 10 second intervals
          MAX_RETRIES=5
          RETRY_COUNT=0
          
          while [ $RETRY_COUNT -lt $MAX_RETRIES ]; do
            echo "Health check attempt $((RETRY_COUNT + 1))/$MAX_RETRIES"
            
            HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" ${{ env.SERVICE_URL }})
            
            if [ "$HTTP_CODE" = "200" ] || [ "$HTTP_CODE" = "304" ]; then
              echo "✅ Frontend health check passed with HTTP $HTTP_CODE!"
              exit 0
            fi
            
            echo "Health check returned HTTP $HTTP_CODE, retrying in 10 seconds..."
            RETRY_COUNT=$((RETRY_COUNT + 1))
            sleep 10
          done
          
          echo "❌ Frontend health check failed after $MAX_RETRIES attempts"
          exit 1

